"""add loki logic

Revision ID: 5cd1b7a60126
Revises: 57eba0a293f2
Create Date: 2025-01-10 14:17:50.188900

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5cd1b7a60126"
down_revision = "57eba0a293f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("services") as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_public",
                sa.Boolean(),
                nullable=False,
                server_default=sa.sql.expression.false(),
            )
        )

    with op.batch_alter_table("users") as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_telegram_premium",
                sa.Boolean(),
                nullable=False,
                server_default=sa.sql.expression.false(),
            )
        )
        batch_op.add_column(
            sa.Column("invited_by", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("last_payment_at", sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "last_telegram_payment_charge_id",
                sa.String(length=64),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "last_provider_payment_charge_id",
                sa.String(length=64),
                nullable=True,
            )
        )
        batch_op.create_foreign_key(
            "fk_invited_by", "users", ["invited_by"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_constraint("fk_invited_by", type_="foreignkey")
        batch_op.drop_column("last_provider_payment_charge_id")
        batch_op.drop_column("last_telegram_payment_charge_id")
        batch_op.drop_column("last_payment_at")
        batch_op.drop_column("invited_by")
        batch_op.drop_column("is_telegram_premium")

    with op.batch_alter_table("services") as batch_op:
        batch_op.drop_column("is_public")

    # ### end Alembic commands ###
